### ISSUE TITLE
Errors on API fetch error

### ISSUE THREAD

**Issue by freyamade** [crnbrdrck/github-user-languages#11]
There's currently no way to display the errors that arise from the API when fetching data.

For example, I got ratelimited by the API earlier but nothing came up to make that known to me, so this is something that should be fixed

**Comment by m-henderson** [comment]
what method in what file calls the api that rate limited you?

**Comment by freyamade** [comment]
The `fetchRepoData` method in `data.ts` as it is the one involved with retrieving data from the GitHub API.

I'll be adding personal tokens in a later update but even that doesn't give unlimited API usage so I would like a small error message to be displayed in the box where we usually draw the chart when an error occurs :smile:

**Comment by freyamade** [comment]
Closed with #15
