### ISSUE TITLE
Pie chart size changes according to number of languages

### ISSUE THREAD

**Issue by Strum355** [crnbrdrck/github-user-languages#28]
# Small
![image](https://user-images.githubusercontent.com/18282288/52233999-7693c500-28b8-11e9-843a-467fabd4d5e9.png)
# Big
![image](https://user-images.githubusercontent.com/18282288/52234005-7b587900-28b8-11e9-8f16-58447f8a9e18.png)
# Extra Big
![image](https://user-images.githubusercontent.com/18282288/52234050-a5aa3680-28b8-11e9-9b8d-8b0df7723e81.png)

**Comment by freyamade** [comment]
This is more of a Chart.js issue and how they handle the legend

Not sure how much I can do as of yet, maybe I'd be able to do something but I'm not sure

**Comment by freyamade** [comment]
Can I get a source where you got these 3 images so I can mess with things a bit and try to improve?

**Comment by Strum355** [comment]
https://github.com/georgewfraser
https://github.com/Strum355
https://github.com/boogluten

**Comment by freyamade** [comment]
Big thanks.

Think I have something that should take care of this issue coming in the next release, just want to do a little bit more testing and make sure it doesn't mess with anything

**Comment by freyamade** [comment]
Deployed :)
