### ISSUE TITLE
Org Pages

### ISSUE THREAD

**Issue by freyamade** [crnbrdrck/github-user-languages#3]
Hey all!

Just a question for you; would you like me to add handling to display the graphs on org pages?

I was going to but I saw that org pages have a "Top Languages" box.

If people want it though, I wouldn't mind adding graphs to org pages as well!

Thanks for reading! :heart:

**Comment by Nuttymoon** [comment]
Hey @crnbrdrck 
First of all, I find this project quite cool!
Drawing the pie on organization pages would still have some value to see the languages ratios.
What would also be lovely is being able to the pie based on lines of code too! But this is a bit out of scope for this issue so I will open a new one 🙂

**Comment by freyamade** [comment]
Hi there!

Thank you very much for your kind words, and for your input!

I definitely think that the pie on organization pages is doable with minimal effort (as far as I'm aware there's an API endpoint for orgs similar to the one I'm using for users).

In terms of displaying by SLOC, it would definitely be cool, I'm just not sure the extent at which it would have to be extended, but we can definitely have a discussion about it! :smile:
