### ISSUE TITLE
Firefox Sync Storage Issues

### ISSUE THREAD

**Issue by freyamade** [crnbrdrck/github-user-languages#30]
The sync storage stuff isn't working on my firefox on my laptop but it is on my PC in work.

It's important to get this working as the settings popup will not be able to work without this, as the inputs will remain greyed out until it properly connects with sync storage

**Comment by freyamade** [comment]
If people could post here if the settings popup works for them and what version of Firefox they are running, it might help me get to the bottom of things a little faster

**Comment by freyamade** [comment]
I think it might be beneficial rewriting the extension to use the WebExtensions API (`browser` instead of `chrome`, promises instead of callbacks) and then polyfilling the `browser` variable into chrome

I think this might solve the issue tbh

**Comment by freyamade** [comment]
I tried the rewrite using the `browser` polyfill and all it did was broke it in Chrome as well.

Settings aren't critical at least, and the firefox thing works as far as the core aspect is concerned

**Comment by freyamade** [comment]
Might have to rewrite from scratch using the refined github project as a base since they seem to have no issue regarding settings in the popup

**Comment by forde-dev** [comment]
> If people could post here if the settings popup works for them and what version of Firefox they are running, it might help me get to the bottom of things a little faster

I'm currently using Firefox 65.0 on Arch Linux, the settings popup does pop up, but I can't enter a token or click the 'show legend' checkbox, otherwise everything seems to work great!.

**Comment by freyamade** [comment]
Yeah I think the cause of that is that the extension can't access the sync storage in the pop-up script

I have the fields initially set to disabled and they enable once the sync storage is accessed so I think that's where the issue is coming from...

Thank you for the help, hopefully I get to the bottom of this, glad you're enjoying it though! :D

**Comment by freyamade** [comment]
@fordetek so I was just about to sit down and start rewriting the extension to target firefox and I noticed that it now works for me? Could you check your install and see if it works again for you also?

**Comment by forde-dev** [comment]
hey Freya, yep, everything works perfect for me now for me too, that's very cool!

**Comment by freyamade** [comment]
Well then.. weird I guess but also awesome!

Thanks for the help friend <3
