### ISSUE TITLE
Pie based on lines of code

### ISSUE THREAD

**Issue by Nuttymoon** [crnbrdrck/github-user-languages#6]
It would be nice to be able to draw the pie based on the number of lines of the total number of lines of code written in every language. This way the pie would give more insight about the developer experience/skills.
And if possible it would be even better to also include repositories to which the developer contributed to into account!

**Comment by freyamade** [comment]
I can have a read through what the GitHub API allows me to do and see if either of these ideas are doable but I think they sound really cool!

I still need to add a small options popup giving control over things like how long to cache for and stuff like that but after that we could (hopefully if the API supports it) have settings to change what is displayed!

**Comment by freyamade** [comment]
Having a look around through the API and it doesn't seem like there is a way to do this via the API.

We could set up on a server a script that would clone all a user's repos and count them locally but that goes beyond the scope of this extension so I'm gonna have to sadly close this as a wontfix :(

**Comment by chylex** [comment]
`https://api.github.com/repos/:user/:repo/languages`
