### ISSUE TITLE
Design Contribution Proposal

### ISSUE THREAD

**Issue by ihtiht** [crnbrdrck/github-user-languages#9]
Hi,

I am a graphic designer. I contribute to open source projects by making designs. At the same time I am creating a portfolio. You can look at my previous studies from my profile. I noticed that this new project has not yet got a logo. And I designed a logo for you. 

![user_languages](https://user-images.githubusercontent.com/36369736/41938072-b6698296-799a-11e8-8ede-749f54b6e240.jpg)

![view](https://user-images.githubusercontent.com/36369736/41938117-d47dcbca-799a-11e8-8650-62e202366001.jpg)

![view1](https://user-images.githubusercontent.com/36369736/41938101-c9b32ff0-799a-11e8-997f-1ccc21d5225d.jpg)

I hope you like. If you want to use it, just specify it. If there is something you want to change or add, please do not hesitate to say it. 

The main idea of ​​design is language and chart. I combined the tail speech balloon and the pie chart.

**Comment by freyamade** [comment]
Hi there!

First off, I would just like to say that this is amazing, both the logo and what you are doing! I am absolutely delighted that you have chosen to create a logo for my little project :smile:

I actually had put in a claim for a logo as part of the [openlogos](https://github.com/arasatasaygin/openlogos) project but I'm actually going to withdraw it now as your logo is amazing!

The one small change I would ask is for to maybe make the tail of the speech bubble a little bigger and the circle a little bit smaller if that would be okay?

Again, thank you so much for this, this is amazing :heart:

**Comment by ihtiht** [comment]
I'm glad you like it, my friend. I am happy to support open source projects. I made improvements about the speech balloon. I made it a little bit more saturated. But as the tail grows we have to shrink the circle because our space is limited. This is because the sizes used in Chrome are 128x128. 
![view son](https://user-images.githubusercontent.com/36369736/41987513-09b8727a-7a42-11e8-84a9-052ed1fc6a8e.PNG)


I guess that looks better. If you think so, I can open a PR.

**Comment by freyamade** [comment]
That looks absolutely fantastic, thank you so much!

When you open the PR, please add your details to the bottom of the README too, in the contributors section :smile:

**Comment by ihtiht** [comment]
I sent a PR with all the necessary files. https://github.com/crnbrdrck/github-user-languages/pull/13

**Comment by freyamade** [comment]
I'll review this once I get home from work :smile:

**Comment by freyamade** [comment]
Merged! Thank you so much again for this!

**Comment by ihtiht** [comment]
You're welcome. If you need a logo for other projects, do not hesitate to say it.
